# Generated by Django 5.1.7 on 2025-03-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reactionreponses', '0001_initial'),
        ('reponses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionreponse',
            name='id_reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reponses.reponse'),
        ),
    ]
