# Generated by Django 5.1.7 on 2025-04-01 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionProbleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='problemes.probleme')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_problemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reactionproblemes',
                'unique_together': {('id_probleme', 'id_utilisateur')},
            },
        ),
    ]
