# Generated by Django 5.1.7 on 2025-03-31 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('id_probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='problemes.probleme')),
            ],
            options={
                'db_table': 'reponses',
            },
        ),
    ]
